[project]
name = "yorzoi"
version = "0.2.1"
description = "Machine learning model that predicts RNA-seq coverage from DNA"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Timon Schneider", email = "mail@timonschneider.de" },
]
dependencies = [
    "packaging",
    "einops>=0.5",
    "matplotlib",
    "pandas",
    "torch>=2.5",
    "wandb",
    "transformers>=4.34.1,<5",
    "numpy>=1.26",
    "pre-commit>=4.3.0",
]

[dependency-groups]
dev = [
    "pytest>=8",
]

[project.urls]
Homepage = "https://github.com/Tom-Ellis-Lab/yorzoi"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
license-files = ["LICENSE.txt"]


[tool.setuptools.packages.find]
include = ["yorzoi*"]
